# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

github: [metadata]

# Site Settings
locale: "en-US"
title: "jsalv blog"
title_separator: "---"
subtitle:
name: "James"
description: "math & data & python & linting & sundry"
baseurl: "/blog"
logo: "/assets/images/jsal_standing.png"
words_per_minute: 200

# Author Settings
author:
  name: "James"
  avatar: "/assets/images/me.jpg"
  bio: ""
  email:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jsalv.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jsal13"

# comments:
#   provider: # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
#   disqus:
#     shortname: # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
#   discourse:
#     server: # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org      : # "light" (default), "dark"
#   utterances:
#     theme: # "github-light" (default), "github-dark"
#     issue_term: # "pathname" (default)
#   giscus:
#     repo_id: # Shown during giscus setup at https://giscus.app
#     category_name: # Full text name of the category
#     category_id: # Shown during giscus setup at https://giscus.app
#     discussion_term: # "pathname" (default), "url", "title", "og:title"
#     reactions_enabled: # '1' for enabled (default), '0' for disabled
#     theme: # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
#   staticman:
#     branch: # "master"
#     endpoint: # "https://{your Staticman v3 API}/v3/entry/github/"

atom_feed:
  path: # blank (default) uses feed.xml
  hide: # true, false (default)

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id:
    anonymize_ip: # true, false (default)

# Site Footer
footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jsalv.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jsal13"

# Reading Files
include:
  - .htaccess
  - _pages
  - assets
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: ""
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:year/:month/:day/:title:output_ext
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      show_date: true
